#############################################################################
# Machine-specific definitions
#
#  This attempts to determine automatically
#  the machine type and OS type.  If it cannot, it gives up and
#  prints a message.
#
# If it fails, you can either add a new automatic test for your machine/OS type, 
# or you can set the necessary variables "manually" here
#############################################################################

# unfortunately, command line arguments to uname are not
# very consistent across UNIX flavours.

osname = $(shell uname -s)
osrelease = $(shell uname -r)

hosttype = unknown

# Test for Solaris 
# If Solaris, we assume we are on a SPARC
ifeq ($(osname),SunOS)
HOSTCFLAGS = -DHOST_IS_BIG_ENDIAN
hosttype = sparcSolaris
endif


# Test for LINUX
# If you are trying to build on Linux on an x86
# try something like this
#
ifeq ($(osname),Linux)
HOSTCFLAGS =
hosttype = x86Linux
endif



